-- Participants table: stores registration form submissions (email + phone + generated id)
create table if not exists public.participants (
  id              bigint generated by default as identity primary key,
  participant_id  text not null,
  email           text not null,
  phone           text not null,
  ui_language     text,
  registered_at   timestamptz,
  received_at     timestamptz default now()
);

alter table public.participants enable row level security;

-- Allow anonymous inserts from the browser (mirrors the feedback policy).
drop policy if exists "anon can insert participants" on public.participants;
create policy "anon can insert participants"
  on public.participants
  for insert
  to anon
  with check (true);

-- Hard limits to discourage abuse since anon can insert
alter table public.participants
  drop constraint if exists participants_participant_id_length_check,
  add  constraint participants_participant_id_length_check
       check (char_length(participant_id) between 1 and 64);

alter table public.participants
  drop constraint if exists participants_email_length_check,
  add  constraint participants_email_length_check
       check (char_length(email) between 3 and 254);

alter table public.participants
  drop constraint if exists participants_phone_length_check,
  add  constraint participants_phone_length_check
       check (char_length(phone) between 3 and 32);

alter table public.participants
  drop constraint if exists participants_ui_language_check,
  add  constraint participants_ui_language_check
       check (ui_language is null or char_length(ui_language) <= 8);
